export const filler_text_par1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquam lorem tellus, nec sodales velit varius vitae. Phasellus scelerisque tortor porttitor laoreet condimentum. Cras sit amet dolor arcu. Vestibulum dapibus magna in magna feugiat ullamcorper. Etiam risus metus, eleifend a dolor at, porta fringilla magna. Nunc sagittis tempus euismod. Duis rutrum condimentum nisl, non eleifend ante. Suspendisse tristique quam eu sem ultricies, at vulputate justo condimentum. Phasellus bibendum lobortis tellus, in commodo est suscipit at. Suspendisse sed arcu ornare erat vulputate lobortis non fermentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ullamcorper scelerisque mi, vel rhoncus eros rutrum sed. Curabitur dignissim turpis molestie, sollicitudin tellus id, dictum libero. Integer consectetur tincidunt mauris, eget tempor dolor egestas at. Ut eget eros molestie, pellentesque arcu sit amet, euismod ante.";

export const filler_text_par2 = "Proin eu turpis id dui tempor vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna congue, molestie massa quis, laoreet sapien. Donec aliquet nisl id blandit molestie. Mauris luctus tincidunt ipsum in vehicula. Vivamus pulvinar turpis vel nunc hendrerit, eu mattis nibh venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mollis cursus varius. Pellentesque pellentesque urna vel mauris hendrerit, quis luctus justo varius. Phasellus vel justo molestie, porta nisl vitae, faucibus orci. Proin orci ipsum, finibus eu lacus nec, auctor pulvinar neque. Praesent sagittis orci sit amet ultrices iaculis. Sed ipsum nulla, hendrerit eu massa a, ultricies convallis orci. Quisque in tincidunt nulla, et faucibus arcu. Cras vulputate rhoncus erat eu tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.";

export const filler_text_par3 = "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam iaculis aliquam mi sed eleifend. Nullam sit amet ex fringilla, placerat ipsum in, venenatis metus. Etiam ut efficitur turpis. Nulla a consequat nisi. In sem felis, vestibulum ac hendrerit nec, porta sed nulla. Praesent venenatis metus purus, sed porta arcu egestas non. Pellentesque tristique scelerisque nunc eget volutpat.";

export const filler_text_long = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

export const filler_text_short = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.";
